spring:
  application:
    name: fulfill
  # 数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ddd_fulfill?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      min-idle: 10
      initial-size: 10
      max-active: 50
      max-wait: 6000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

server:
  port: 8015

dubbo:
  scan:
    base-packages: com.ruyuan.fulfill.rpc
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28015
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: warehouse,logistics,risk

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

rocketmq:
  name-server: localhost:9876