spring:
  application:
    name: risk

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

server:
  port: 8018

dubbo:
  scan:
    base-packages: com.ruyuan.risk.rpc
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: 28018
  consumer:
    check: false
  provider:
    threads: 800
    actives: 200
  cloud:
    subscribed-services: